name: tomato
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.18.1
  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppinsregular.ttf
        - asset: assets/fonts/poppinsmedium.ttf
        - asset: assets/fonts/poppinssemibold.ttf
        - asset: assets/fonts/poppinsbold.ttf
        - asset: assets/fonts/poppinsextra.ttf

    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
